/**
 * Assessment data constants for the 13-step Wellness Assessment.
 *
 * PLUGGABLE SEAMS for Sheila's answers:
 *   Q4 → MEDICAL_CONDITIONS (swap this array when she provides her list)
 *   Q5 → BASELINE_RATING_ITEMS (currently 26 items from spec; trim if she confirms 23)
 *   Q6 → Roadmap logic lives in the ATM slotting Edge Function, not here
 *   Q7 → AI Coach system prompt lives in the AI coach Edge Function, not here
 */

// ── Q4 SEAM: Medical conditions list (dev-proposed, awaiting Sheila) ──
export const MEDICAL_CONDITIONS = [
  "IBS (Irritable Bowel Syndrome)",
  "IBD (Inflammatory Bowel Disease)",
  "Crohn's Disease",
  "Celiac Disease",
  "GERD / Acid Reflux",
  "SIBO",
  "Leaky Gut (diagnosed or suspected)",
  "PCOS (Polycystic Ovary Syndrome)",
  "PMOS (Polycystic Metabolic Ovary Syndrome)",
  "Endometriosis",
  "Fibroids",
  "Hashimoto's Thyroiditis",
  "Hypothyroidism",
  "Hyperthyroidism",
  "Graves' Disease",
  "Type 2 Diabetes",
  "Pre-diabetes / Insulin Resistance",
  "Type 1 Diabetes",
  "Metabolic Syndrome",
  "Anxiety Disorder",
  "Depression",
  "PTSD",
  "ADHD",
  "Bipolar Disorder",
  "Autoimmune condition (other)",
  "Rheumatoid Arthritis",
  "Lupus (SLE)",
  "Multiple Sclerosis",
  "Psoriasis",
  "Eczema / Atopic Dermatitis",
  "Fibromyalgia",
  "Chronic Fatigue Syndrome",
  "Lyme Disease",
  "Mold Illness / CIRS",
  "Anemia / Iron Deficiency",
  "Vitamin D Deficiency",
  "B12 Deficiency",
  "Osteoporosis / Osteopenia",
  "High Blood Pressure",
  "High Cholesterol",
  "Heart Disease",
  "Stroke",
  "Cancer (any type)",
  "Eating Disorder (past or current)",
  "Infertility",
  "Recurrent Miscarriage",
  "Gestational Diabetes",
  "Preeclampsia",
  "Postpartum Depression",
  "Migraines",
  "Seizure Disorder / Epilepsy",
  "Sleep Apnea",
  "Asthma",
  "Allergies (environmental)",
];

// ── Symptom Inventory (Step 6) — from spec sections 6.1-6.8 ──
export const SYMPTOM_CATEGORIES = [
  {
    key: "symptoms_gut",
    label: "Gut & Digestive Symptoms",
    subcategories: [
      {
        label: "Digestive & GI",
        symptoms: [
          "Bloating especially after meals",
          "Abdominal distension",
          "Excessive or painful gas",
          "Burping",
          "Acid reflux or heartburn",
          "Nausea",
          "Early satiety (getting full quickly)",
          "Delayed stomach emptying",
          "Constipation",
          "Diarrhea",
          "Alternating constipation and diarrhea",
          "Loose stools",
          "Pale stools",
          "Floating stools",
          "Undigested food in stool",
          "Mucus in stool",
          "Foul-smelling stool",
          "Incomplete bowel movements",
          "Urgency to use the bathroom",
          "IBS-type symptoms",
        ],
      },
      {
        label: "Gut Barrier & Immune",
        symptoms: [
          "Food sensitivities or reactions",
          "New food intolerances",
          "Worsening symptoms with healthy foods",
          "Histamine reactions",
          "Hives or rashes after eating",
          "Flushing",
          "Itching",
          "Sinus congestion after meals",
          "Frequent infections",
          "Autoimmune flares",
          "Elevated inflammation markers on labs",
          "Leaky gut type symptoms",
        ],
      },
      {
        label: "Nutrient Absorption",
        symptoms: [
          "Iron deficiency (diagnosed or suspected)",
          "B12 deficiency (diagnosed or suspected)",
          "Folate deficiency (diagnosed or suspected)",
          "Magnesium deficiency (diagnosed or suspected)",
          "Fat-soluble vitamin deficiencies (A, D, E, K)",
          "Easy bruising",
          "Brittle nails",
          "Hair thinning or hair loss",
          "Dry skin",
          "Cracks at corners of mouth",
          "Burning tongue",
          "Glossitis (inflamed tongue)",
        ],
      },
    ],
  },
  {
    key: "symptoms_metabolic",
    label: "Metabolic Symptoms",
    subcategories: [
      {
        label: "Blood Sugar Instability",
        symptoms: [
          "Reactive hypoglycemia",
          "Blood sugar crashes",
          "Shakiness between meals",
          "Dizziness",
          "Lightheadedness",
          "Sweating not related to temperature",
          "Anxiety after meals",
          "Irritability when hungry",
          "Hangry episodes",
          "Needing to eat frequently to feel okay",
          "Nighttime hunger",
          "Waking between 2-4am",
          "Sugar cravings",
          "Carbohydrate cravings",
          "Salt cravings",
        ],
      },
      {
        label: "Energy & Weight",
        symptoms: [
          "Chronic fatigue",
          "Post-meal fatigue",
          "Afternoon energy crashes",
          "Exercise intolerance",
          "Poor recovery from workouts",
          "Feeling worse with calorie restriction",
          "Weight gain despite dieting",
          "Weight gain concentrated in abdomen",
          "Inability to lose weight",
          "Rapid weight gain",
          "Weight cycling (losing and regaining repeatedly)",
          "Loss of lean muscle",
          "Increased fat storage under stress",
        ],
      },
      {
        label: "Metabolic Stress Signals",
        symptoms: [
          "Cold intolerance",
          "Heat intolerance",
          "Low body temperature",
          "Cold hands and feet",
          "Elevated resting heart rate",
          "Blood pressure swings",
          "Elevated fasting insulin on labs",
          "Elevated triglycerides on labs",
          "Elevated fasting glucose on labs",
          "Elevated A1C or normal A1C but still symptomatic",
        ],
      },
    ],
  },
  {
    key: "symptoms_hormonal",
    label: "Hormone-Related Symptoms",
    subcategories: [
      {
        label: "Menstrual & Reproductive",
        symptoms: [
          "Irregular cycles",
          "Short cycles (less than 24 days)",
          "Long cycles (more than 35 days)",
          "Missed periods",
          "Heavy periods",
          "Painful periods",
          "Clotting",
          "Spotting between periods",
          "PMS symptoms",
          "PMDD symptoms",
          "Ovulation pain",
          "Infertility",
          "Recurrent miscarriage",
          "Perimenopause symptoms",
          "Early menopause",
        ],
      },
      {
        label: "Estrogen & Progesterone Imbalance",
        symptoms: [
          "Breast tenderness",
          "Fibrocystic breasts",
          "Migraines especially hormonal",
          "Fluid retention",
          "Swelling",
          "Endometriosis symptoms",
          "Fibroids",
          "Mood swings",
          "Anxiety",
          "Depression",
          "Low stress tolerance",
          "Insomnia especially in the second half of the cycle",
        ],
      },
      {
        label: "Cortisol & Stress Hormones",
        symptoms: [
          "Wired but tired feeling",
          "Anxiety without a clear cause",
          "Panic attacks",
          "Poor stress resilience",
          "Crashing after stressful events",
          "Feeling on edge",
          "Burnout",
          "Sleep disruption",
          "Early morning waking",
          "Difficulty falling asleep",
          "Night sweats",
        ],
      },
      {
        label: "Thyroid-Related",
        symptoms: [
          "Fatigue",
          "Brain fog",
          "Hair thinning",
          "Hair loss including outer eyebrows",
          "Dry skin",
          "Constipation",
          "Cold intolerance",
          "Hoarseness",
          "Puffy face",
          "Swollen neck sensation",
          "Difficulty swallowing that comes and goes",
          "Low motivation",
          "Depression",
          "Menstrual irregularities",
        ],
      },
    ],
  },
  {
    key: "symptoms_neuro",
    label: "Neurological & Cognitive Symptoms",
    subcategories: [
      {
        label: "Neurological & Cognitive",
        symptoms: [
          "Brain fog",
          "Poor concentration",
          "Memory issues",
          "Word-finding difficulty",
          "ADHD-like symptoms",
          "Anxiety",
          "Depression",
          "Mood instability",
          "Irritability",
          "Low motivation",
          "Emotional reactivity",
          "Feeling overwhelmed easily",
          "Dissociation",
          "Panic symptoms",
        ],
      },
    ],
  },
  {
    key: "symptoms_skin",
    label: "Skin, Hair & Connective Tissue",
    subcategories: [
      {
        label: "Skin, Hair & Connective Tissue",
        symptoms: [
          "Acne especially along the jawline",
          "Adult-onset acne",
          "Rosacea",
          "Eczema",
          "Psoriasis",
          "Rashes",
          "Hives",
          "Itching",
          "Dry skin",
          "Oily skin",
          "Hair thinning",
          "Hair shedding",
          "Brittle nails",
          "Ridged nails",
          "Slow wound healing",
          "Easy bruising",
          "Stretch marks",
          "Cellulite changes",
        ],
      },
    ],
  },
  {
    key: "symptoms_cardio",
    label: "Cardiovascular & Fluid Regulation",
    subcategories: [
      {
        label: "Cardiovascular & Fluid Regulation",
        symptoms: [
          "Palpitations",
          "Tachycardia (racing heart)",
          "Blood pressure swings",
          "Orthostatic hypotension (dizziness on standing)",
          "Dizziness on standing",
          "Swelling in ankles or hands",
          "Water retention",
          "Puffy face",
          "Head pressure",
          "Exercise intolerance",
        ],
      },
    ],
  },
  {
    key: "symptoms_sexual",
    label: "Sexual Health & Libido",
    subcategories: [
      {
        label: "Sexual Health & Libido",
        symptoms: [
          "Low libido",
          "Vaginal dryness",
          "Pain with intercourse",
          "Recurrent UTIs",
          "Recurrent yeast infections",
          "Recurrent bacterial vaginosis",
          "Pelvic discomfort",
        ],
      },
    ],
  },
  {
    key: "symptoms_systemic",
    label: "Systemic & Unexplained Symptoms",
    subcategories: [
      {
        label: "Systemic & Unexplained",
        symptoms: [
          "Feeling off but labs are normal",
          "Symptoms that do not fit one diagnosis",
          "Symptoms that worsen with dieting",
          "Feeling worse with fasting",
          "Feeling worse with intense exercise",
          "Feeling worse under stress",
          "Symptoms that come and go",
          "Symptoms that worsen cyclically with the menstrual cycle",
          "Being told it is just anxiety",
          "Being told results are normal despite feeling unwell",
        ],
      },
    ],
  },
];

// ── Q5 SEAM: Baseline rating items (26 from spec; Sheila may trim to 23) ──
export const BASELINE_RATING_ITEMS = [
  {
    category: "Gut & Digestion",
    items: [
      { key: "gut_bloating", label: "Bloating after meals" },
      { key: "gut_regularity", label: "Bowel regularity" },
      { key: "gut_comfort", label: "Digestive comfort overall" },
      { key: "gut_reflux", label: "Acid reflux or heartburn" },
      { key: "gut_reactions", label: "Food reactions" },
    ],
  },
  {
    category: "Energy & Metabolism",
    items: [
      { key: "energy_day", label: "Energy levels throughout the day" },
      { key: "energy_afternoon", label: "Afternoon energy crashes" },
      { key: "energy_cravings", label: "Sugar or carbohydrate cravings" },
      { key: "energy_between_meals", label: "Ability to go between meals without symptoms" },
      { key: "energy_sleep", label: "Sleep quality" },
    ],
  },
  {
    category: "Hormones & Cycle",
    items: [
      { key: "hormone_mood", label: "Mood stability throughout the month" },
      { key: "hormone_pms", label: "PMS symptom severity" },
      { key: "hormone_cycle", label: "Cycle regularity (if applicable)" },
      { key: "hormone_flashes", label: "Hot flashes or night sweats (if applicable)" },
      { key: "hormone_skin_hair", label: "Hair and skin changes" },
    ],
  },
  {
    category: "Nervous System & Stress",
    items: [
      { key: "ns_stress", label: "Overall stress level" },
      { key: "ns_relax", label: "Ability to relax" },
      { key: "ns_anxiety", label: "Anxiety level" },
      { key: "ns_overwhelm", label: "Feeling of being overwhelmed" },
      { key: "ns_racing_mind", label: "Racing mind at night" },
    ],
  },
  {
    category: "Brain & Cognition",
    items: [
      { key: "brain_clarity", label: "Mental clarity and focus" },
      { key: "brain_memory", label: "Memory" },
      { key: "brain_fog", label: "Brain fog" },
    ],
  },
  {
    category: "Overall Wellbeing",
    items: [
      { key: "overall_vitality", label: "Overall energy and vitality" },
      { key: "overall_confidence", label: "Confidence in understanding your body" },
      { key: "overall_motivation", label: "Motivation to continue the program" },
    ],
  },
];

// ── Step 7 options ──
export const DIETS_TRIED = [
  "Keto",
  "Intermittent Fasting",
  "Low Fat",
  "Vegan",
  "Elimination",
  "Gluten Free",
  "Dairy Free",
  "Other",
];

// ── Step 9 options ──
export const STRESS_SOURCES = [
  "Work",
  "Finances",
  "Relationships",
  "Health",
  "Family",
  "Other",
];

export const COPING_MECHANISMS = [
  "Exercise",
  "Meditation",
  "Therapy",
  "Journaling",
  "None",
  "Other",
];

// ── Step 10 options ──
export const MOVEMENT_BARRIERS = [
  "Time",
  "Energy",
  "Pain",
  "Motivation",
  "Access",
  "None",
];
